#pragma once

#include <vector>

// Street lamps, and the light they cast.
//
// Two halves that share one mechanism:
//
//   1. Lamps a town ALREADY has. 95 of the 5381 maps place a lamp-shaped prop of
//      their own -- Henesys 2, Magatia 5, Amoria 5, Kerning 4, Ludibrium 3. Those are
//      already art-directed onto the right pavement, so the system does not replace
//      them; it finds them in the map's own obj list and hangs a light on each.
//   2. Lamps a town does NOT have. Ellinia has none, so lamps are injected at
//      hand-picked positions (g_aManualLamps) and lit the same way.
//
// Either way the LIGHT is a separate object from the POST. The post is ordinary
// scenery: present in daylight, tinted with the map at night, and never faded out --
// a lamp post does not vanish at noon. Only the light switches.
//
// EMITTERS ARE PER SPRITE AND THERE CAN BE SEVERAL. A lamp is not a point light:
// the Henesys post carries three globes, New Leaf City's three heads, Magatia's two,
// and the candelabra three candles. Hanging one glow on a sprite's centroid puts the
// light in the empty air between them. weather_lamptable.inc carries the measured
// position of every separate light on every known lamp, generated by
// obj_lamp_emitters.py.
//
// See IMPLEMENTATION.md for the day/night system this rides on.

class CMapLoadable;
class CompatInPacket;
struct IWzGr2DLayer;
template <class T> class ZRefCountedPtr;

#include "ztl/ztl.h"

// ---------------------------------------------------------------- field lifecycle

// Append this map's glow objects (and any injected lamp posts) to the field's own obj
// list, so the engine's normal LoadMap builds them natively. MUST be called BEFORE
// CMapLoadable::LoadMap: building an object with a direct MakeObj call afterwards
// faults. bSky is the weather module's own field filter -- lamps exist only where
// night happens, because a map that never darkens has nothing to switch on.
void Lamps_Inject(CMapLoadable* pField, bool bSky);

// After the engine's LoadMap has built everything: snap the switch level to the
// current time rather than warming up, the same reason the night tint snaps on entry.
void Lamps_OnFieldLoaded();

// The graphics-detail rebuild (System Options) calls RestoreObj without passing
// LoadMap, destroying and rebuilding every object including ours.
void Lamps_OnObjRebuild(bool bBefore);

void Lamps_OnLeaveField();

// ---------------------------------------------------------------- per frame

// Advance the photocell and the per-lamp warm-up, then re-assert every lamp and glow
// layer. Called from the weather module's Update, inside its apply gate.
void Lamps_Update();

// Called every frame REGARDLESS of the apply gate, and on every stage. Places a
// pending `!lamp` preview: that has to happen on the main thread and must not be
// skipped by the daytime optimisation, or previewing a lamp at noon would do nothing.
void Lamps_Tick();

// The colour a scenery layer at this position should be, with any nearby lamp light
// folded in. For layers the weather module does not own and so cannot relight -- the
// foliage sway swaps a plant for generated frames, and those are not in its object list.
// Falls back to the plain night tint when nothing is lit, so it is always safe to call.
unsigned int Lamps_SceneryColorAt(float x, float y);

// True while at least one lamp on this map is emitting. False all day, which is what
// lets the caller skip the relight entirely.
bool Lamps_HasLights();

// Lift the night tint back toward daylight around each LIT lamp. Runs AFTER the
// uniform scenery pass and overwrites only the layers near a light. Backgrounds are
// deliberately not passed: they parallax, so their distance to a lamp is not stable.
void Lamps_RelightScenery(std::vector<IWzGr2DLayerPtr>& vTiles,
                          std::vector<IWzGr2DLayerPtr>& vObjs,
                          std::vector<IWzGr2DLayerPtr>& vNpc,
                          float fNight, float fNpcScale);

// ---------------------------------------------------------------- capture

// Offered every layer the engine builds, FIRST in the capture chain. Returns true if
// this layer is one of ours, in which case the caller must not file it anywhere else.
bool Lamps_CaptureLayer(const IWzGr2DLayerPtr& pLayer);

void Lamps_Attach();

// ---------------------------------------------------------------- shared map geometry

// One foothold segment in world coordinates.
//
// This lives here because lamps got to it first: a lamp has to stand ON the ground, so
// it already had to read the field's foothold list. The sway filter needs the same list
// for the opposite reason, to find the plants that are NOT standing on anything, and
// two copies of a WZ walker that have to agree about the same data is how they stop
// agreeing.
struct FHSEG { long x1, y1, x2, y2; };

// Read every foothold segment out of a field property. Safe to call BEFORE
// CMapLoadable::LoadMap: the property tree is fully populated by then, which is what
// lets Lamps_Inject place a lamp on the ground before a single object exists.
void Lamps_CollectFootholds(IWzPropertyPtr pPropField, std::vector<FHSEG>& out);

// ---------------------------------------------------------------- !lamp preview
//
// LP 0x373F, from server/lamp/LampPackets.java. Runs on the RECEIVE thread, so it
// only records the request; the placement happens on the next frame.
void Lamp_HandlePreviewPacket(CompatInPacket* pPacket);

// How many lamps the table knows about, so the server and the DLL can be checked
// against each other rather than trusting a hardcoded count.
int Lamp_TableSize();
