#include "stdafx.h"
#include "weather.h"
#include "weatherfx.h"
#include "weathercanvas.h"
#include "lamps.h"
#include "debug.h"
#include "wvs/util.h"
#include "ztl/ztl.h"
#include <cmath>
#include <climits>
#include <vector>

// Foliage that BENDS rather than slides.
//
// The first version moved the whole sprite a couple of pixels, which slid the base along
// the ground with the top: a plant on a conveyor belt rather than a plant in the wind.
// A real sway keeps the base planted and leans everything above it, which is a SHEAR, and
// IWzGr2DLayer has no shear. So the lean lives in the pixels, generated by
// weathercanvas.cpp from the object's own sprite.
//
// HOW THE FRAMES WORK
// -------------------
// Each object gets SWAY_FRAMES sheared copies of itself, spanning the full storm lean from
// hard left to hard right. Calm weather cycles through the MIDDLE few; a storm uses the
// whole set. So the strength of the wind costs nothing at runtime: it is which frames get
// shown, not a regeneration.
//
// Every frame is generated at the SAME canvas size, padded for the widest lean, so
// switching between them cannot move the sprite. That is why the pad is passed in rather
// than derived per frame.
//
// ONE LAYER PER FRAME, and only one visible at a time. The alternative is swapping the
// canvas on a single layer, which means calling RemoveCanvas and InsertCanvas on a layer
// the ENGINE owns, several times a second, forever. Toggling `visible` is one property
// write and cannot leave a map object with no canvas at all.
//
// The original object layer is HIDDEN, not modified. If anything here fails the worst case
// is putting its visibility back, which is also exactly what teardown does.

// ODD, AND THAT IS NOT A PREFERENCE. The shear for frame i is (i - n/2) / (n/2), so an
// EVEN count has no frame at zero: at 10 the range comes out -1.0 .. +0.8, every plant
// leans further left than right, and calm weather centres on a frame that is already
// tilted. 11 is the odd count next to the 10 that was asked for.
#define SWAY_FRAMES       11      // odd, so there is a true upright in the middle
#define SWAY_FRAMES_BIG    7      // ...and fewer for a big sprite, see the budget below
#define SWAY_BIG_PIXELS  18000    // above this a sprite counts as big
// Objects that may sway, per field.
//
// 72 was cutting Henesys by 18 plants: it generates 90 sway entries and the loop that
// builds them stops at the cap, in object order, so the last fifth of the map's greenery
// simply never moved. Clump splitting made it worse by design -- four mushrooms in one
// sprite are four entries now, not one.
//
// The MEMORY limiter is SWAY_PIXEL_BUDGET, and all 90 of Henesys' entries fit inside it at
// 71%. This count was a second, blunter limit measuring the wrong thing: a hundred small
// plants cost less than three bushes. 128 leaves the budget as the only real ceiling,
// which is where the decision belongs.
#define SWAY_MAX_OBJ     128
#define SWAY_MAX_PIXELS  (360 * 320)   // one object may not be larger than this

// TOTAL generated pixels allowed across every swaying object on a map: 8M pixels at 4
// bytes each, so about 32 MB. Frames are the whole cost of this feature: nine copies of a
// 290x239 shrub is 2.5 MB on its own, and a dense map would happily ask for hundreds. The
// budget is what makes raising the size ceiling safe.
//
// Raised from 6M when bushes were admitted: Henesys alone was already at 77% of the old
// figure and the bush took it to 95%, which leaves no room for a denser map and makes the
// budget cut -- which drops objects SILENTLY in a release build -- a live risk rather than
// a backstop.
//
// The honest fix is not a bigger number. Every INSTANCE builds its own frames, so the 18
// copies of acc1/grassySoil/nature/13 in Henesys generate 18 identical frame sets and
// account for roughly 44% of the whole budget on that map by themselves. Layers can share
// a canvas, so caching frames per (sprite, clump) and pointing every instance at the same
// set would cut this by the instance count. That is the change to make if this is ever
// tight again.
#define SWAY_PIXEL_BUDGET (8 * 1024 * 1024)
// MEASURED OFF A REFERENCE CAPTURE, rather than guessed.
//
// Tools note: 137 frames of a 30fps capture were tracked by the sunflower head's centroid
// (Tools has no script for it; it was a one-off crop-and-centroid over the extracted
// frames). The head travelled 13.2 px peak to peak on a plant 221 px tall -- +-0.030 of
// its own height -- on a clean sine with peaks 39 frames apart, i.e. a 1.30 s period.
//
// So calm wants +-0.030 and a 1.3 s cycle. Calm is SWAY_CALM_FRAC of SWAY_LEAN_MAX, so
// 0.50 x 0.060 lands exactly on it and leaves storm at 0.060, twice calm, which is the
// separation the old 3/4 span had lost.
//
// A FRACTION, not a frame count, and that is load bearing. It used to be "2 frames either
// side of upright", which silently encoded SWAY_FRAMES = 9: raising the frame count makes
// each step smaller, so the same 2 steps would have quietly cut the calm amplitude by a
// third and un-calibrated it from the reference above. Expressed as a fraction of the
// half-range, the amplitude survives any frame count and only the resolution changes.
//
// THIS SPEEDS THE SWAY UP, reversing an earlier "much slower would look better". That
// request came before the pivot fix, when plants were shearing about their waists: what
// read as too much movement was mostly the distortion, not the rate. The reference is the
// better authority now, but the two numbers to move back are right here.
#define SWAY_LEAN_MAX   0.060f    // storm lean; calm is half of it, see the span below
// The least a plant's top should travel at full lean, in pixels. Below this the motion is
// there in the numbers and invisible on screen.
#define SWAY_MIN_TRAVEL      5.0f
// ...but a 12 px sprite must not be scaled up 4x into a windscreen wiper.
#define SWAY_SMALL_BOOST_MAX 2.2f
#define SWAY_CALM_FRAC     0.50f  // of the half-range, in fair weather
#define SWAY_EXPOSED_FRAC  0.75f  // ...for the third of plants that read as more exposed
// High wind used to take the WHOLE half-range, i.e. the full SWAY_LEAN_MAX. That is the
// most the generated frames can do, so it also meant a storm was pinned at the ceiling
// with nothing above it; backing off leaves the top of the range as headroom and stops a
// gale reading as every plant slapping its own limit.
#define SWAY_ROUGH_FRAC    0.85f
// Slowed hard. A plant in a breeze moves at the pace of the breeze, and at 2.6 s a
// calm bush was ticking over like a metronome; 6.2 s reads as air moving rather than
// as an animation playing. Storm goes 0.85 -> 2.4 s for the same reason -- fast enough
// to look driven, slow enough not to vibrate.
#define SWAY_PERIOD_CALM 1300.0f
#define SWAY_PERIOD_ROUGH 700.0f
// Rope and ladder move SLOWLY, on their own clock, about two and a half times the
// foliage period. A heavy pendulum has a long period, so a wooden ladder that moves
// little but quickly reads as jitter, while the same small movement drawn out over six
// seconds reads as weight. That is the whole difference and it is timing, not distance.
#define SWAY_PERIOD_ROPE_CALM  6400.0f
#define SWAY_PERIOD_ROPE_ROUGH 2400.0f
// Objects to build per frame. Forty objects at nine frames each is 360 canvas
// generations, and doing them all on the frame the map loads is a visible stall.
#define SWAY_BUILD_PER_FRAME 2

// Two rope or ladder segments closer than this horizontally are one structure.
//
// A long ladder is not one object: it is a column of segments stacked end to end. Swayed
// independently they slide apart at every joint, because each restarts its lean from its
// own base and each is on its own phase. Grouping fixes both: one phase for the column,
// and each segment leaning from the bottom of the WHOLE column via nBaseOffset.
#define SWAY_STACK_DX      30

// How much of a rope hangs rigid below its anchor before it starts to bend.
//
// A rope tied to a stake does not curve at the knot: the top is held straight and the free
// length below it swings. 0.5 puts the bend in the bottom half, which is what a rope
// hanging off a post actually does. Measured down the whole COLUMN, so a long rope made of
// several segments has one rigid head rather than a stiff patch at every joint.
#define SWAY_ROPE_RIGID_FRAC 0.5f

// Foliage sprites that are SEVERAL plants in one bitmap, and where each plant is.
// GENERATED by foliage_clumps.py. See weather_clumps.inc for how the rects are
// found; the short version is that connectivity alone stops at the ground, so plants
// rooted in the same tuft need their upper bodies and their column density looked at too.
#define CLUMP_MAX 4
struct CLUMPDEF {
    const wchar_t* sOS;
    const wchar_t* sL0;
    const wchar_t* sL1;
    const wchar_t* sL2;
    int  nCount;
    struct { int x0, y0, x1, y1; } a[CLUMP_MAX];
};
static const CLUMPDEF kClumps[] = {
#include "weather_clumps.inc"
};

// Hashed the same way Weather_ObjPathHash does it, so a row can be found from an object
// without either side holding a WZ string. Built once, on first use.
static unsigned long long ClumpHashPart(unsigned long long h, const wchar_t* s) {
    h ^= 0x2Fu; h *= 1099511628211ULL;
    for (; s && *s; ++s) {
        wchar_t c = *s;
        if (c >= L'A' && c <= L'Z') c = (wchar_t)(c - L'A' + L'a');
        h ^= (unsigned long long)c;
        h *= 1099511628211ULL;
    }
    return h;
}

// Props that are not filed as foliage but move like it, and HOW FAR DOWN they bend.
//
// fPivotFrac is where the bend starts, as a fraction of the sprite's height: 1.0 is the
// base (an ordinary plant, rooted at the ground), 0.55 means the bottom 55% is rigid and
// only the top leans. The shear already clamps every row BELOW the pivot to no movement,
// so a high pivot is exactly "only the top sways" and costs nothing extra.
//
// A standing hay bundle is the case this exists for: it is tied at the waist, so the
// straw above the binding moves and the bale itself does not.
struct EXTRASWAY {
    const wchar_t* sOS; const wchar_t* sL0; const wchar_t* sL1; const wchar_t* sL2;
    float fPivotFrac;
};
static const EXTRASWAY kExtraSway[] = {
    { L"acc1", L"grassySoil", L"market", L"20", 0.55f },   // Henesys standing hay, 140x114 x4
    // Mushroom Shrine's two landmark trees.  The lower trunk stays rigid; only the
    // upper crown and its long branches bend.  These are explicit because their 520+
    // pixel canvases are intentionally above the normal foliage safety band.
    { L"globalJP", L"flowerViewing", L"nature", L"0",  0.62f },
    { L"globalJP", L"flowerViewing", L"nature", L"10", 0.68f },
};

static const EXTRASWAY kLargeTreeSway[] = {
    { L"globalJP", L"flowerViewing", L"nature", L"0",  0.62f },
    { L"globalJP", L"flowerViewing", L"nature", L"10", 0.68f },
};

// Deliberate whitelist for loose map art with a clear upper attachment point.
// `nullptr` in l2 means every numbered variant of that family. Town lamps are
// intentionally absent: they are fixed street furniture, not hanging fixtures.
struct HANGINGSWAY {
    const wchar_t* sOS; const wchar_t* sL0; const wchar_t* sL1; const wchar_t* sL2;
};
static const HANGINGSWAY kHangingSway[] = {
    { L"acc3",           L"skyStation",    L"ivy",       nullptr },
    { L"dungeon3",       L"dragonValley",  L"cage",      nullptr },
    { L"KualaLumpur_MY", L"Field",         L"banner",    nullptr },
    { L"KualaLumpur_MY", L"Field",         L"mobBanner", nullptr },
    { L"Tdungeon3",      L"basic",         L"xBanner",   nullptr },
    { L"masteriaGL1",    L"crimsonwoodMT", L"flag",      nullptr },
    { L"house",          L"darkWood",      L"lamp",      nullptr },
    { L"halloweenGL",    L"halloween",     L"room3",     L"lamp" },
    { L"halloweenGLR",   L"halloween",     L"room3",     L"lamp" },
    // Shop and station signs that are mounted from above, rather than ground signposts.
    { L"101BuildingTW",  L"101BuildingSubway", L"signBoard", nullptr },
    { L"NightMarketTW",  L"NightMarketField",  L"SignBoard", nullptr },
    { L"Tdungeon3",      L"ani",           L"signboard", nullptr },
    { L"Tdungeon3",      L"shopPart1",     L"mainSign",  nullptr },
    { L"Tdungeon3",      L"shopPart1",     L"sideSign",  nullptr },
    { L"Tdungeon3",      L"shopPart2",     L"mainSign",  nullptr },
    { L"Tdungeon3",      L"shopPart2",     L"miniSign",  nullptr },
    { L"Tdungeon3",      L"shopPart2",     L"sideSign",  nullptr },
};

static bool PartEqualsI(const wchar_t* actual, const wchar_t* expected) {
    return expected == nullptr || (actual && _wcsicmp(actual, expected) == 0);
}

bool WeatherSway_IsHangingObject(const wchar_t* sOS, const wchar_t* sL0,
                                 const wchar_t* sL1, const wchar_t* sL2) {
    for (const HANGINGSWAY& entry : kHangingSway) {
        if (PartEqualsI(sOS, entry.sOS) && PartEqualsI(sL0, entry.sL0)
            && PartEqualsI(sL1, entry.sL1) && PartEqualsI(sL2, entry.sL2)) {
            return true;
        }
    }
    return false;
}

// HEAD OVERLAYS THAT ARE PURE DUPLICATES, AND SO ARE SWITCHED OFF RATHER THAN SWAYED.
//
// Henesys' tall stalks ship as two obj entries: the plant, and a second sprite pinned to
// the same corner holding a differently shaded copy of its caps, cross-fading over two
// frames to make the head shimmer. Swaying the two together works, but the overlay adds
// nothing worth the frames it costs -- so these are hidden and the plant draws its own
// head, which it already contains.
//
// That last clause is the whole safety argument and it was measured, not assumed. Diffing
// each overlay against the plant's own top rows:
//
//   nature/25 vs nature/11   0 pixels opaque in the overlay where the plant is not
//   nature/26 vs nature/12   0 pixels opaque in the overlay where the plant is not
//
// So hiding one cannot cut a silhouette; every pixel it covers has plant underneath. What
// goes away is the shading difference (the caps settle to the plant's own colours) and the
// shimmer. Colours DO differ where they overlap, by up to 204 on a channel, which is why
// this is a visible change and not dead art.
//
// Listed by sprite rather than detected generically on purpose. The pairing test below --
// same left edge, same width, shorter, top within 3 px -- is a good structural match but
// it cannot tell a redundant duplicate from an overlay that carries art of its own. Any
// composition NOT on this list keeps the paired sway, which is correct behaviour and was
// verified in game; only what is known redundant is switched off.
struct DEADOVERLAY { const wchar_t* sOS; const wchar_t* sL0; const wchar_t* sL1; const wchar_t* sL2; };
static const DEADOVERLAY kDeadOverlay[] = {
    { L"acc1", L"grassySoil", L"nature", L"25" },   // caps of nature/11, 132x183, 2 frames
    { L"acc1", L"grassySoil", L"nature", L"26" },   // caps of nature/12, 120x157, 2 frames
};

// A MEASURED TRANSPARENT PIXEL PER SPRITE, for the CopyEx shear path's clear.
//
// See weather_clearpx.inc and PROJECT::nClearX. Only sprites whose top-left corner is NOT
// already transparent are listed; x = -1 means the sprite has no transparent pixel at all,
// which on this path means it cannot be cleared and so must not sway.
struct CLEARPX { unsigned long long uHash; int x, y; };
static const CLEARPX kClearPx[] = {
#include "weather_clearpx.inc"
    { 0ULL, -1, -1 },   // sentinel: the .inc can legitimately generate no rows
};

// Where to clear this sprite from. Returns false when it has nowhere transparent at all.
static bool ClearPixelFor(unsigned long long uHash, int* px, int* py) {
    *px = -1; *py = -1;
    if (!uHash) {
        return true;
    }
    for (size_t i = 0; i < _countof(kClearPx); ++i) {
        if (kClearPx[i].uHash == uHash) {
            *px = kClearPx[i].x;
            *py = kClearPx[i].y;
            return kClearPx[i].x >= 0;
        }
    }
    return true;      // not listed: its corner is already transparent
}

static unsigned long long ExtraHash(const EXTRASWAY& e);
static unsigned long long DeadOverlayHash(const DEADOVERLAY& e);

// Is this sprite a head overlay we have decided adds nothing? Same hash matching as
// WeatherSway_ExtraFoliagePivot, for the same reason: no one has to own a WZ string.
static bool IsDeadOverlay(unsigned long long uHash) {
    static unsigned long long s_a[_countof(kDeadOverlay)];
    static bool s_bReady = false;
    if (!s_bReady) {
        for (size_t i = 0; i < _countof(kDeadOverlay); ++i) s_a[i] = DeadOverlayHash(kDeadOverlay[i]);
        s_bReady = true;
    }
    if (!uHash) {
        return false;
    }
    for (size_t i = 0; i < _countof(kDeadOverlay); ++i) {
        if (s_a[i] == uHash) return true;
    }
    return false;
}

// Matched by the same path hash weather.cpp stamps on every object, so neither side has
// to hold a WZ string. Returns the pivot fraction, or 0 when this is not one of them.
float WeatherSway_ExtraFoliagePivot(unsigned long long uHash) {
    static unsigned long long s_a[_countof(kExtraSway)];
    static bool s_bReady = false;
    if (!s_bReady) {
        for (size_t i = 0; i < _countof(kExtraSway); ++i) s_a[i] = ExtraHash(kExtraSway[i]);
        s_bReady = true;
    }
    if (!uHash) {
        return 0.0f;
    }
    for (size_t i = 0; i < _countof(kExtraSway); ++i) {
        if (s_a[i] == uHash) {
            return kExtraSway[i].fPivotFrac;
        }
    }
    return 0.0f;
}

bool WeatherSway_IsLargeTree(unsigned long long uHash) {
    static unsigned long long s_a[_countof(kLargeTreeSway)];
    static bool s_bReady = false;
    if (!s_bReady) {
        for (size_t i = 0; i < _countof(kLargeTreeSway); ++i) s_a[i] = ExtraHash(kLargeTreeSway[i]);
        s_bReady = true;
    }
    for (size_t i = 0; i < _countof(kLargeTreeSway); ++i) {
        if (s_a[i] == uHash) return true;
    }
    return false;
}

bool WeatherSway_IsLeafreTreeObject(const wchar_t* sOS, const wchar_t* sL0,
                                    const wchar_t* sL1) {
    if (!sOS || !sL0 || !sL1 || _wcsicmp(sL1, L"nature1") != 0) {
        return false;
    }
    return (_wcsicmp(sOS, L"acc6") == 0 && _wcsicmp(sL0, L"minar") == 0)
        || (_wcsicmp(sOS, L"dungeon3") == 0 && _wcsicmp(sL0, L"dragonRoad") == 0);
}

bool WeatherSway_IsLeafreTreeBack(const wchar_t* sBS, int nNo) {
    if (!sBS || _wcsicmp(sBS, L"minar") != 0) return false;
    // These are the four large leafy tree layers used by Leafre town.  Keep the
    // selection narrow: `minar` also contains sky, rock and architecture backs.
    return nNo == 8 || nNo == 9 || nNo == 11 || nNo == 14;
}

void WeatherSway_ReplaceLeafreBack(const IWzGr2DLayerPtr& pLayer) {
    if (!pLayer || !WeatherCanvas_Probe()) return;
    try {
        IWzCanvasPtr src = pLayer->Getcanvas();
        if (!src) return;
        const int w = src->width, h = src->height;
        if (w <= 0 || h <= 0 || w > 900 || h > 640) return;

        // The lower trunk remains still.  The back layer itself stays intact, so its
        // native parallax and camera tracking continue to be owned by the engine.
        const int pivot = (int)((float)h * 0.68f);
        const float leanMax = 0.024f;      // calmer than foreground foliage
        const int pad = (int)(leanMax * (float)h) + 3;
        IWzCanvasPtr frame[5];
        for (int i = 0; i < 5; ++i) {
            const float f = (float)(i - 2) * 0.5f;
            PROJECT cfg{};
            cfg.fLean = leanMax * f;
            cfg.fSquash = 1.0f;
            cfg.fAlpha = 1.0f;
            cfg.bKeepColour = true;
            cfg.nPadOverride = pad;
            cfg.nPivotRow = pivot;
            cfg.nClearX = -1;
            cfg.nClearY = -1;
            POINT anchor{};
            int actualPivot = pivot;
            frame[i] = WeatherCanvas_Project(src, cfg, &anchor, &actualPivot);
            if (!frame[i]) return;
            // The added pad must not shift the tree inside its existing parallax layer.
            frame[i]->cx = src->cx + anchor.x;
            frame[i]->cy = src->cy + anchor.y - actualPivot;
        }

        // A map back begins with one static canvas.  Replacing that set on the SAME
        // layer (rather than creating world-space overlays) is what preserves parallax.
        try { pLayer->Animate(GA_STOP); } catch (const _com_error&) {}
        for (int i = 7; i >= 0; --i) {
            try { pLayer->RemoveCanvas(i); } catch (const _com_error&) {}
        }
        for (int i = 0; i < 5; ++i) {
            pLayer->InsertCanvas(frame[i], 750, 255, 255);
        }
        pLayer->Animate(GA_REPEAT);
    } catch (const _com_error&) {
        // Leave the original back untouched if the client declines a canvas operation.
    }
}

static unsigned long long ExtraHash(const EXTRASWAY& e) {
    unsigned long long h = 1469598103934665603ULL;
    h = ClumpHashPart(h, e.sOS);
    h = ClumpHashPart(h, e.sL0);
    h = ClumpHashPart(h, e.sL1);
    h = ClumpHashPart(h, e.sL2);
    return h;
}

static unsigned long long DeadOverlayHash(const DEADOVERLAY& e) {
    unsigned long long h = 1469598103934665603ULL;
    h = ClumpHashPart(h, e.sOS);
    h = ClumpHashPart(h, e.sL0);
    h = ClumpHashPart(h, e.sL1);
    h = ClumpHashPart(h, e.sL2);
    return h;
}

static const CLUMPDEF* ClumpsForHash(unsigned long long uWant) {
    static unsigned long long s_a[_countof(kClumps)];
    static bool s_bReady = false;
    if (!s_bReady) {
        for (size_t i = 0; i < _countof(kClumps); ++i) {
            unsigned long long h = 1469598103934665603ULL;
            h = ClumpHashPart(h, kClumps[i].sOS);
            h = ClumpHashPart(h, kClumps[i].sL0);
            h = ClumpHashPart(h, kClumps[i].sL1);
            h = ClumpHashPart(h, kClumps[i].sL2);
            s_a[i] = h;
        }
        s_bReady = true;
    }
    if (!uWant) {
        return nullptr;
    }
    for (size_t i = 0; i < _countof(kClumps); ++i) {
        if (s_a[i] == uWant) {
            return &kClumps[i];
        }
    }
    return nullptr;
}

namespace {

// Worked out for every candidate before ANY frame is generated, because a segment cannot
// know its own offset until the whole column is known.
struct Plan {
    int  nObj;
    unsigned char kind;
    int  ltx, lty, sw, sh;
    int  nPivotRow;       // where the object is rooted, from its placement
    int  nBaseOffset;     // height of everything stacked below this segment
    // Depth below the column's anchor that does not move: the stake a rope is tied to.
    // Column-wide, so a stacked rope has one rigid head rather than one per segment.
    int  nRigidDepth;
    // WHAT THIS OBJECT'S TIMING IS KEYED ON, and how tall the thing it belongs to is.
    //
    // Normally itself. For a rope or ladder column it is the WHOLE column, and that is the
    // difference between a ladder that bends and one that looks spliced: SetSwayTiming
    // hashes the object index for tempo, amplitude and second-harmonic phase, so segments
    // of one ladder were each running at their own rate and their own swing width. Sharing
    // fPhase alone -- which the join pass already did -- is not enough; two segments on the
    // same phase but different rates still pull apart, and the joints are exactly where it
    // shows. The height matters for the same reason: a 40 px rung classified as "short"
    // moves like a mushroom, when what it is part of is a 300 px ladder.
    int  nTimingObj;
    int  nTimingH;
    float fPhase;         // shared across a column
    // The window of the sprite this entry bends. Empty means the whole thing, which is
    // every ordinary plant; a sprite holding four mushrooms yields four Plans, one per
    // mushroom, each with its own window and so its own pivot and its own phase.
    RECT rcClump;
    int  nClumpIdx;       // which clump of the sprite, or -1 for the whole thing
    unsigned long long uHash;   // the sprite's path hash, the cache key
};

struct SwayObj {
    int    nObj;
    IWzGr2DLayer* apFrame[SWAY_FRAMES];
    int    nFrames;       // 9 normally, fewer for a big sprite
    int    nShown;        // which frame is visible, or -1
    float  fPhase;
    float  fSpan;         // how far it leans
    unsigned char kind;   // decides the period: rope swings slower than foliage
    float  fRate;         // radians per ms: this plant's own tempo
    float  fWobble;       // phase of its second harmonic
    // What fraction of the half-range this plant uses in fair weather, in percent. Percent
    // rather than frames so it does not have to know how many frames it got: a big sprite
    // is built with fewer, and the frame count is a memory decision, not an amplitude one.
    unsigned char uSpanPct;
    // Where this plant is, in LAYER space, so it can ask the lamps how lit it is. Stored
    // rather than read per frame: it never moves, and reading it back would be a COM call
    // per plant per frame.
    int    nLitX, nLitY;
};

std::vector<SwayObj> g_v;
bool g_bBuilt = false;
bool g_bUsable = false;
int  g_nScan = -1;         // how far through the object list the build has got, -1 done
int  g_nPixels = 0;        // generated so far, against SWAY_PIXEL_BUDGET
std::vector<Plan> g_vPlan;

// Map objects switched off outright rather than swayed: the redundant head overlays.
//
// Kept separate from g_v because there is nothing to animate and nothing to release --
// only a visible flag on a layer the MAP owns, which has to be handed back the way the
// swayed originals are.
std::vector<int> g_vHidden;

// GENERATED FRAMES, SHARED BETWEEN EVERY INSTANCE OF THE SAME SPRITE.
//
// Henesys places acc1/grassySoil/nature/13 eighteen times. Each copy was generating its
// own identical set of sheared canvases, and those eighteen sets alone were most of the
// map's frame budget -- which is why Henesys ran out at 77 of 103 plants and Ellinia hit
// the object cap. The frames depend only on the sprite, the clump, and the lean, and all
// of those are identical across instances: the pivot is `entryY - layerTop`, which is the
// sprite's own origin row, the same for every placement.
//
// Layers can share a canvas, so each instance still gets its own layer at its own
// position while pointing at one set of pixels. Ropes are excluded: a ladder segment's
// frames depend on how far down the column it sits, so no two are alike.
struct FrameSet {
    unsigned long long uHash;
    int   nClump;
    int   nFrames;
    int   nAnchorX, nAnchorY, cw, ch, nPivot;
    IWzCanvasPtr apCanvas[SWAY_FRAMES];
};
std::vector<FrameSet> g_vFrameCache;

FrameSet* FindFrameSet(unsigned long long uHash, int nClump) {
    if (!uHash) {
        return nullptr;
    }
    for (size_t i = 0; i < g_vFrameCache.size(); ++i) {
        if (g_vFrameCache[i].uHash == uHash && g_vFrameCache[i].nClump == nClump) {
            return &g_vFrameCache[i];
        }
    }
    return nullptr;
}

void Release(IWzGr2DLayer*& p) {
    if (!p) {
        return;
    }
    try { p->visible = 0; } catch (...) {}
    p->Release();
    p = nullptr;
}

IWzGr2DLayer* MakeLayer(IWzCanvasPtr pCanvas, int x, int y, int w, int h, int nZ) {
    try {
        IWzGr2DPtr& pGr = get_gr();
        if (!pGr || !pCanvas) {
            return nullptr;
        }
        IWzGr2DLayerPtr made = pGr->CreateLayer(x, y, w, h, nZ,
                                                static_cast<IUnknown*>(pCanvas),
                                                Ztl_variant_t());
        if (!made) {
            return nullptr;
        }
        made->visible = 0;          // built hidden; the tick reveals exactly one
        IWzGr2DLayer* p = made;
        p->AddRef();
        return p;
    } catch (const _com_error&) {
        return nullptr;
    }
}

// HOW FAST THIS PARTICULAR PLANT MOVES.
//
// One period for the whole map makes a field of plants read as a single animation playing
// on many sprites. Three things break that up here, none of which touches a generated
// canvas -- so the frame cache still shares one set of pixels between every instance.
//
// 1. HEIGHT. Not the pendulum law, which would make tall plants uniformly slowest and is
//    monotonic and dull. Tall things are slow and heavy, waist-high shrubs are the
//    liveliest thing in a breeze, and something tiny and close to the ground is sheltered
//    by everything around it and moves less than the shrub. So the curve dips in the
//    middle: slow, fast, slower.
// 2. A per-plant jitter of a few percent, so two shrubs side by side never lock together.
// 3. A second harmonic at a per-plant phase, so the path is not a clean sine. This is what
//    reads as "fluid": a pure sine looks mechanical however well it is timed.
#define SWAY_TALL_PX      170     // above this a plant is heavy and slow
#define SWAY_SHORT_PX      64     // below this it is low, sheltered, and unhurried
#define SWAY_RATE_TALL   1.55f    // period multipliers; larger is slower
#define SWAY_RATE_MED    0.82f
#define SWAY_RATE_SHORT  1.02f    // was 1.18: short plants read as sluggish next to the shrubs
#define SWAY_JITTER      0.09f    // +- this much on the period, per plant
#define SWAY_WOBBLE      0.16f    // how much of the second harmonic is mixed in

static void SetSwayTiming(SwayObj* pOut, int nHeight, int nObj) {
    float fScale;
    if (nHeight >= SWAY_TALL_PX) {
        fScale = SWAY_RATE_TALL;
    } else if (nHeight <= SWAY_SHORT_PX) {
        fScale = SWAY_RATE_SHORT;
    } else {
        // Eased between the two ends rather than stepped, or a plant one pixel over a
        // threshold moves visibly differently from its neighbour.
        const float t = (float)(nHeight - SWAY_SHORT_PX)
                      / (float)(SWAY_TALL_PX - SWAY_SHORT_PX);
        fScale = (t < 0.5f)
               ? (SWAY_RATE_SHORT + (SWAY_RATE_MED - SWAY_RATE_SHORT) * (t * 2.0f))
               : (SWAY_RATE_MED + (SWAY_RATE_TALL - SWAY_RATE_MED) * ((t - 0.5f) * 2.0f));
    }
    // Two independent hashes of the index: one nudges the tempo, the other places the
    // second harmonic. Stable per object, so a rebuild puts a plant back on its own beat.
    const unsigned int h1 = (unsigned int)nObj * 2654435761u;
    const unsigned int h2 = ((unsigned int)nObj + 0x9E37u) * 2246822519u;
    fScale *= 1.0f + SWAY_JITTER * (((float)(h1 % 2000u) / 1000.0f) - 1.0f);
    pOut->fRate = 6.2831853f / (fScale > 0.05f ? fScale : 0.05f);   // scaled at use
    pOut->fWobble = (float)(h2 % 6283u) / 1000.0f;
    // Amplitude varies too, and it has to come from the FRAME RANGE rather than the lean,
    // because the lean is baked into the canvases the cache shares. Half the half-range is
    // the measured reference; a third of plants take three quarters and read as more
    // exposed.
    pOut->uSpanPct = (unsigned char)(((h2 >> 11) % 3u == 0u)
                                     ? (int)(SWAY_EXPOSED_FRAC * 100.0f)
                                     : (int)(SWAY_CALM_FRAC * 100.0f));
}

// Build every frame for one object. Returns false and leaves nothing behind on failure,
// so the caller can simply leave the original layer visible and unswayed.
bool BuildFrames(const Plan& pl, SwayObj* pOut) {
    const int nObj = pl.nObj;
    const unsigned char kind = pl.kind;
    IWzGr2DLayerPtr pObj;
    POINT pt = {0, 0};
    if (!Weather_GetObj(nObj, pObj, &pt) || !pObj) {
        return false;
    }
    IWzCanvasPtr pSrc;
    int nZ = 0;
    const int sw = pl.sw, sh = pl.sh, ltx = pl.ltx, lty = pl.lty;
    try {
        pSrc = pObj->Getcanvas();
        if (!pSrc) {
            return false;
        }
        nZ = pObj->z;
    } catch (const _com_error&) {
        return false;
    }
    // Landmark trees are the only sprites allowed beyond the normal 360x320 cap.
    // Their two WZ paths are whitelisted above and their shared frame cache means each
    // art family pays this cost once, even where the map places it more than once.
    const int nMaxPixels = (kind == 4 /*SWAY_TREE*/)
                         ? (900 * 600)
                         : WeatherSway_IsLargeTree(pl.uHash) ? (560 * 740)
                         : SWAY_MAX_PIXELS;
    if (sw <= 0 || sh <= 0 || sw * sh > nMaxPixels) {
        return false;
    }
    // A big sprite gets fewer frames. The cycle is slightly steppier and nobody looking at
    // a swaying shrub will see it, whereas nine copies of one would eat a quarter of the
    // whole map's budget.
    const int nFrames = (sw * sh > SWAY_BIG_PIXELS) ? SWAY_FRAMES_BIG : SWAY_FRAMES;

    // A ladder moves LESS than a plant, not more. Hanging signs and fixtures
    // are lighter, but still restrained so they read as wind rather than a swing.
    //
    // Went 1.9 -> 0.45 -> 0.18. The first was backwards, on the reasoning that a hanging
    // thing swings further than a rooted one; these are heavy wooden ladders and thick
    // rigging and they barely move. 0.18 is a suggestion of movement rather than a sway,
    // which is also the kindest setting for the stacked segments: whatever misalignment
    // survives between them scales with the lean.
    // A LEAN PROPORTIONAL TO HEIGHT IS INVISIBLE ON A SHORT PLANT.
    //
    // The reference amplitude, +-0.030 of height, was measured on a 221 px sunflower where
    // it is a clear 6.6 px. The same fraction on a 40 px mushroom is 1.2 px -- under a
    // pixel and a half of travel, which is why the small plants read as standing still
    // however much the tall ones move. Real small plants are also lighter and genuinely do
    // move proportionally more, so this is not a fudge.
    //
    // Short sprites are scaled up until they travel at least SWAY_MIN_TRAVEL px at full
    // lean, capped so a tiny sprite cannot fling itself across the screen. A tall plant is
    // already past the floor and is left exactly where the measurement put it.
    float fSpan = (kind == 2 /*SWAY_ROPE*/) ? 0.18f
                : (kind == 3 /*SWAY_HANGING*/) ? 0.26f : 1.0f;
    // A 500 px canopy has much more leverage than a sunflower.  It still needs
    // visible movement, but 70% keeps the bend calm rather than rubbery.
    if (kind == 4 /*SWAY_TREE*/) fSpan = 0.70f;
    if (kind == 1 /*SWAY_FOLIAGE*/) {
        const float fTravel = SWAY_LEAN_MAX * (float)sh;
        if (fTravel > 0.5f && fTravel < SWAY_MIN_TRAVEL) {
            fSpan = SWAY_MIN_TRAVEL / fTravel;
            if (fSpan > SWAY_SMALL_BOOST_MAX) fSpan = SWAY_SMALL_BOOST_MAX;
        }
    }
    const float fMax = SWAY_LEAN_MAX * fSpan;
    // The window this entry bends, and where it sits inside the sprite. An empty rect is
    // the whole sprite, which is the ordinary case.
    const bool bClump = (pl.rcClump.right > pl.rcClump.left);
    const int cx0 = bClump ? (int)pl.rcClump.left : 0;
    const int cy0 = bClump ? (int)pl.rcClump.top : 0;
    const int chh = bClump ? (int)(pl.rcClump.bottom - pl.rcClump.top) : sh;
    // Every frame shares this pad, so the widest lean fits and no frame is offset
    // relative to any other.
    // Room for the widest lean of this segment INCLUDING the displacement it inherits
    // from everything below it, or the top of a tall ladder is clipped off.
    // Room for the widest lean this segment reaches, which for a hanging column includes
    // how far down the column it already is.
    const int nPad = (int)(fMax * (float)(chh + pl.nBaseOffset)) + 2;

    IWzGr2DLayer* apMade[SWAY_FRAMES] = {nullptr};
    int nAnchorX = 0, nAnchorY = 0, cw = 0, ch = 0, nPivot = sh - 1;

    // A rope's frames depend on its depth in the column, so every segment is unique and
    // there is nothing to share. Everything else is identical across placements.
    const bool bShare = (kind != 2 /*SWAY_ROPE*/) && pl.uHash != 0;
    FrameSet* pCached = bShare ? FindFrameSet(pl.uHash, pl.nClumpIdx) : nullptr;
    if (pCached && pCached->nFrames == nFrames) {
        nAnchorX = pCached->nAnchorX; nAnchorY = pCached->nAnchorY;
        cw = pCached->cw; ch = pCached->ch; nPivot = pCached->nPivot;
        for (int i = 0; i < nFrames; ++i) {
            const int x = (ltx + cx0) - nAnchorX;
            const int y = (lty + cy0 + nPivot) - nAnchorY;
            apMade[i] = MakeLayer(pCached->apCanvas[i], x, y, cw, ch, nZ);
            if (!apMade[i]) {
                for (int k = 0; k <= i; ++k) Release(apMade[k]);
                return false;
            }
        }
        try { pObj->visible = 0; } catch (const _com_error&) {}
        pOut->nObj = nObj;
        for (int i = 0; i < SWAY_FRAMES; ++i) {
            pOut->apFrame[i] = (i < nFrames) ? apMade[i] : nullptr;
        }
        pOut->nFrames = nFrames;
        pOut->nShown = -1;
        // No pixels generated: this instance costs layers, not canvases. Not charging the
        // budget here is the entire point of the cache.
        pOut->fPhase = pl.fPhase;
        pOut->fSpan = fSpan;
        pOut->kind = kind;
        pOut->nLitX = ltx + cx0 + (bClump ? (int)(pl.rcClump.right - pl.rcClump.left) : sw) / 2;
        pOut->nLitY = lty + cy0 + chh / 2;
        SetSwayTiming(pOut, (pl.nTimingH > 0) ? pl.nTimingH : chh, pl.nTimingObj);
        return true;
    }

    // Where this sprite can be cleared from, and whether it can be at all. Only the blit
    // path reads it; on a client with a pixel buffer both values stay -1 and are ignored.
    int nClearX = -1, nClearY = -1;
    if (!ClearPixelFor(pl.uHash, &nClearX, &nClearY) && !WeatherCanvas_HasPixelPath()) {
        // Fully opaque sprite on the blit path: every frame would come out inside a solid
        // box of its own colour. Leaving it standing still is the better failure.
        LOG_ONCE_PER_ID((int)(pl.uHash & 0x7FFFFFFF),
                        "weathersway: sprite %08X has no transparent pixel and the blit path "
                        "cannot clear around it; left unswayed rather than boxed",
                        (unsigned)(pl.uHash & 0xFFFFFFFF));
        return false;
    }

    IWzCanvasPtr apCanvas[SWAY_FRAMES];
    for (int i = 0; i < nFrames; ++i) {
        // -1 at frame 0, 0 in the middle, +1 at the last.
        const float f = (float)(i - nFrames / 2) / (float)(nFrames / 2);
        PROJECT cfg;
        cfg.fLean = fMax * f;
        cfg.fSquash = 1.0f;      // a sway does NOT flatten: only a shadow does
        cfg.fAlpha = 1.0f;
        cfg.nBlur = 0;           // the sprite's own edges, unchanged
        cfg.uR = 0; cfg.uG = 0; cfg.uB = 0;   // ignored: fKeepColour below
        cfg.bKeepColour = true;
        cfg.nPadOverride = nPad;
        cfg.nClearX = nClearX;
        cfg.nClearY = nClearY;
        cfg.nBaseOffset = pl.nBaseOffset;
        cfg.nRigidDepth = pl.nRigidDepth;
        cfg.bHangFromTop = (kind == 2 /*SWAY_ROPE*/ || kind == 3 /*SWAY_HANGING*/);
        // Window-relative, because the projection measures everything from the window.
        cfg.nPivotRow = bClump ? (pl.nPivotRow - cy0) : pl.nPivotRow;
        if (cfg.nPivotRow < 0) cfg.nPivotRow = 0;
        if (cfg.nPivotRow > chh - 1) cfg.nPivotRow = chh - 1;
        if (bClump) {
            cfg.rcSrc.left = cx0;   cfg.rcSrc.top = cy0;
            cfg.rcSrc.right = pl.rcClump.right; cfg.rcSrc.bottom = pl.rcClump.bottom;
        }

        POINT anchor = {0, 0};
        int nBaseRow = pl.nPivotRow;
        IWzCanvasPtr pFrame = WeatherCanvas_Project(pSrc, cfg, &anchor, &nBaseRow);
        if (!pFrame) {
            for (int k = 0; k < i; ++k) Release(apMade[k]);
            return false;
        }
        if (i == 0) {
            try {
                cw = pFrame->width;
                ch = pFrame->height;
            } catch (const _com_error&) {
                return false;
            }
            nAnchorX = anchor.x;
            nAnchorY = anchor.y;
            nPivot = nBaseRow;
        }
        // Line the generated sprite's PIVOT ROW up with where that same row sits in the
        // original. Using the canvas bottom instead is what left padded sprites hovering
        // and swinging from a point below the plant.
        const int x = (ltx + cx0) - nAnchorX;
        const int y = (lty + cy0 + nPivot) - nAnchorY;
        apCanvas[i] = pFrame;
        apMade[i] = MakeLayer(pFrame, x, y, cw, ch, nZ);
        if (!apMade[i]) {
            for (int k = 0; k <= i; ++k) Release(apMade[k]);
            return false;
        }
    }
    if (bShare) {
        FrameSet fs;
        fs.uHash = pl.uHash; fs.nClump = pl.nClumpIdx; fs.nFrames = nFrames;
        fs.nAnchorX = nAnchorX; fs.nAnchorY = nAnchorY;
        fs.cw = cw; fs.ch = ch; fs.nPivot = nPivot;
        for (int i = 0; i < nFrames; ++i) fs.apCanvas[i] = apCanvas[i];
        g_vFrameCache.push_back(fs);
    }

    // Only now is it safe to hide the original: every replacement exists.
    try { pObj->visible = 0; } catch (const _com_error&) {}

    pOut->nObj = nObj;
    for (int i = 0; i < SWAY_FRAMES; ++i) {
        pOut->apFrame[i] = (i < nFrames) ? apMade[i] : nullptr;
    }
    pOut->nFrames = nFrames;
    pOut->nShown = -1;
    g_nPixels += cw * ch * nFrames;
    pOut->fPhase = pl.fPhase;
    pOut->fSpan = fSpan;
    pOut->kind = kind;
    // The middle of the plant, which is what the lamp light should be sampled at: its base
    // alone would miss a tall plant leaning into a pool of light above it.
    pOut->nLitX = ltx + cx0 + (bClump ? (int)(pl.rcClump.right - pl.rcClump.left) : sw) / 2;
    pOut->nLitY = lty + cy0 + chh / 2;
    SetSwayTiming(pOut, (pl.nTimingH > 0) ? pl.nTimingH : chh, pl.nTimingObj);
    return true;
}

// One pass over every candidate: read its geometry, then join rope and ladder segments
// that share a column so they lean as one structure.
void BuildPlan() {
    g_vPlan.clear();
    // Why each candidate was dropped. Guessing at this from the screen has cost several
    // rounds: "not swaying" looks the same whichever filter did it.
    int nSeen = 0, nNotFoliage = 0, nNoLayer = 0, nBadGeom = 0, nNotRooted = 0, nPaired = 0;
    int nDead = 0;
    const int n = Weather_ObjCount();

    // A PLANT WHOSE OWN HEAD IS A SECOND OBJECT.
    //
    // Henesys' tall stalks are drawn as TWO obj entries pinned to one corner: the whole
    // plant (acc1/grassySoil/nature/11, 132x294, one frame) and a copy of its top 183 rows
    // (nature/25, same width, TWO frames) that cross-fades in alpha to make the head
    // shimmer. nature/12 + nature/26 are the same pair. Four such plants exist on the map.
    //
    // The overlay has a second frame, so Weather_NoteObjProp demotes it to SWAY_NONE --
    // correct for a butterfly, wrong here. It was then never sheared and never hidden,
    // while the stalk beneath it leant its head 15 px each way: a pixel-registered copy of
    // the plant's top, standing perfectly still. That is the "frozen copy" report, and no
    // amount of work on our own layers could have touched it, because it is the map's.
    //
    // They are swayed as ONE plant: the overlay is given the stalk's phase and an
    // nBaseOffset equal to how far its base sits above the stalk's, so it leans by exactly
    // the amount the stalk has already leant at that height -- the same mechanism that
    // keeps a stacked ladder in one piece.
    struct OBJBOX { int ltx, lty, w, h; unsigned char kind; bool bUsed; };
    std::vector<OBJBOX> vBox((size_t)n);
    for (int i = 0; i < n; ++i) {
        OBJBOX& b = vBox[(size_t)i];
        b.ltx = b.lty = b.w = b.h = INT_MIN;
        b.kind = Weather_ObjSwayKind(i);
        b.bUsed = false;
        IWzGr2DLayerPtr pb;
        POINT ptb = {0, 0};
        if (!Weather_GetObj(i, pb, &ptb) || !pb) {
            continue;
        }
        try {
            IWzCanvasPtr cb = pb->Getcanvas();
            IWzVector2DPtr ltb = pb->Getlt();
            if (!cb || !ltb) continue;
            b.ltx = ltb->x; b.lty = ltb->y; b.w = cb->width; b.h = cb->height;
        } catch (const _com_error&) {
        }
    }
    // The overlay's top row may be a pixel off its plant's.
    const int kOverlayDY = 3;
    for (int i = 0; i < n && (int)g_vPlan.size() < SWAY_MAX_OBJ; ++i) {
        const unsigned char kind = Weather_ObjSwayKind(i);
        if (kind == 0) {
            ++nNotFoliage;
            continue;
        }
        ++nSeen;
        IWzGr2DLayerPtr p;
        POINT pt = {0, 0};
        if (!Weather_GetObj(i, p, &pt) || !p) {
            ++nNoLayer;
            continue;
        }
        Plan pl;
        pl.nObj = i;
        pl.kind = kind;
        pl.nBaseOffset = 0;
        pl.nRigidDepth = 0;      // needs pl.sh, so it is set once the geometry is read
        pl.nTimingObj = i;       // itself, unless a column claims it below
        pl.nTimingH = 0;         // 0 means "use my own height"
        try {
            IWzCanvasPtr c = p->Getcanvas();
            IWzVector2DPtr lt = p->Getlt();
            if (!c || !lt) {
                continue;
            }
            pl.sw = c->width;
            pl.sh = c->height;
            pl.ltx = lt->x;
            pl.lty = lt->y;
        } catch (const _com_error&) {
            continue;
        }
        if (pl.sw <= 0 || pl.sh <= 0) {
            ++nBadGeom;
            continue;
        }
        // A lone rope with no column to join: the rigid head is a fraction of its own
        // length. The join pass overwrites this for anything that turns out to be stacked,
        // where the fraction has to be of the WHOLE column.
        if (kind == 2 /*SWAY_ROPE*/) {
            pl.nRigidDepth = (int)((float)pl.sh * SWAY_ROPE_RIGID_FRAC);
        }
        // Where the engine roots it: the obj entry's y is where the canvas origin goes.
        // Read without looking at a pixel, which matters on this client because
        // _LockAddress returns no buffer and the alpha scan cannot run at all.
        //
        // THE ORIGIN IS NOT THE BASE, and assuming it was is what made plants stretch.
        // Measured over all 969 foliage sprites in Map/Obj: 92.4% put the origin in the
        // MIDDLE of the canvas (35-65% of the height) and only 1.7% put it at the base.
        // Shearing about a mid-sprite pivot leans the top one way and the bottom the
        // OTHER way, so the plant scissors around its waist instead of bending from the
        // ground -- exactly the "it stretches and is not rooted" report.
        //
        // So the origin is a FLOOR on the pivot, not the pivot. Anything that claims to be
        // rooted above the bottom eighth of its own canvas is overruled and rooted there
        // instead. A sprite whose origin really is at its base (that 1.7%) is unchanged,
        // because its origin already sits below this line.
        pl.nPivotRow = pt.y - pl.lty;
        // FOLIAGE ONLY. A ladder is a COLUMN of segments and the stacking below computes
        // each segment's nBaseOffset from `lty + sh`, i.e. from its canvas bottom. Moving
        // its pivot off that row breaks the arithmetic that keeps the segments joined, so
        // they shear from the wrong line and the ladder comes apart at every rung -- which
        // is exactly what applying this floor to everything did to it.
        const float fExtra = WeatherSway_ExtraFoliagePivot(Weather_ObjPathHash(i));
        if (kind == 4 /*SWAY_TREE*/) {
            // Leafre's `nature1` art contains the whole trunk and crown in one canvas.
            // Lock the lower 65% so its roots and thick main trunk remain planted.
            pl.nPivotRow = (int)((float)pl.sh * 0.65f);
        } else if (fExtra > 0.0f) {
            // Bends from partway up, not from the ground: everything below this row is
            // clamped by the shear and stays put.
            pl.nPivotRow = (int)((float)pl.sh * fExtra);
        } else if (pl.kind == 1 /*SWAY_FOLIAGE*/) {
            const int nFloorRow = (int)((float)pl.sh * 0.88f);
            if (pl.nPivotRow < nFloorRow) pl.nPivotRow = nFloorRow;
        } else {
            // ROPES, LADDERS AND EXPLICIT HANGING ART hang from their top row.
            //
            // They are fixed to something above and swing further the further down you
            // go, which is the opposite of a plant. Anchoring at the top and letting the
            // shear run downward is what makes a ladder bend as one hanging thing instead
            // of leaning like a mast.
            //
            // The origin is no use here: 93% of the 1655 rope and ladder sprites put it
            // mid canvas, which pinned the middle and left the two halves disagreeing.
            pl.nPivotRow = 0;
        }
        if (pl.nPivotRow < 0) pl.nPivotRow = 0;
        if (pl.nPivotRow > pl.sh - 1) pl.nPivotRow = pl.sh - 1;
        // SEVERAL PLANTS IN ONE SPRITE become several entries.
        //
        // A shear has one pivot, so four mushrooms in one bitmap all lean about the base
        // of the bitmap: the outer two swing through an arc instead of standing on their
        // stems. Each clump gets its own Plan, and so its own window, its own pivot at its
        // own base, and its own phase -- which is also what stops a row of mushrooms
        // moving in lockstep.
        //
        // The frame budget barely notices: the clumps PARTITION the sprite rather than
        // copy it, so the pixels are the same set carved up, plus one lot of lean padding
        // per clump instead of one for the sprite.
        pl.rcClump.left = pl.rcClump.top = pl.rcClump.right = pl.rcClump.bottom = 0;
        pl.nClumpIdx = -1;
        pl.uHash = Weather_ObjPathHash(i);
        const CLUMPDEF* pClump = (kind == 1 /*SWAY_FOLIAGE*/)
                               ? ClumpsForHash(Weather_ObjPathHash(i)) : nullptr;

        // Foliage only, and only where there is actually a platform under it.
        //
        // A plant bends because it is rooted. One hung in front of a platform's face, or
        // sitting on the very lip of one, has no root to bend from and reads as a sprite
        // being waved about. HERE and not in the name classifier, because the test needs
        // the sprite's bottom row and the classifier only has the obj entry's y, which is
        // the canvas origin and frequently nowhere near the base.
        //
        // Ropes and ladders are exempt by definition: they hang from an anchor above and
        // meet the ground at the far end from it, so testing their placement point
        // against a foothold would silence every one of them.
        //
        // THE PROBE IS THE OBJECT'S PLACEMENT POINT, and the window has to scale with the
        // sprite. Neither end of the canvas is reliably the ground: the old probe used the
        // canvas BOTTOM, which is below the plant on any sprite with padding, and the entry
        // point itself sits a median 62 px and a mean 94 px ABOVE the canvas bottom because
        // 92% of foliage origins are mid canvas. Against a fixed 38 px window that rejected
        // 76% of all foliage -- the "most plants do not sway" report.
        //
        // The anchor is somewhere INSIDE the sprite, so it is between the ground and one
        // sprite-height above it. Passing the height lets the test say exactly that, and it
        // still rejects a plant that is nowhere near a foothold, which is its whole job.
        if (kind == 1 /*SWAY_FOLIAGE*/
                && !WeatherSway_IsLargeTree(Weather_ObjPathHash(i))
                && !Weather_RootedWellInside(pt.x, pt.y, pl.sh)) {
            ++nNotRooted;
            continue;
        }
        // Independent by default. Only columns get joined below.
        pl.fPhase = (float)((i * 2654435761u) % 6283u) / 1000.0f;
        // Emit the head overlay alongside its plant, on the plant's own phase -- or, for
        // the ones on kDeadOverlay, switch it off and let the plant draw its own head.
        {
            for (int j = 0; j < n; ++j) {
                const OBJBOX& b = vBox[(size_t)j];
                if (j == i || b.w == INT_MIN || b.kind != 0 || b.bUsed) continue;
                if (b.ltx != pl.ltx || b.w != pl.sw || b.h >= pl.sh) continue;
                const int dy = b.lty - pl.lty;
                if (dy < -kOverlayDY || dy > kOverlayDY) continue;
                if (IsDeadOverlay(Weather_ObjPathHash(j))) {
                    IWzGr2DLayerPtr pOv;
                    POINT ptOv = {0, 0};
                    if (Weather_GetObj(j, pOv, &ptOv) && pOv) {
                        try { pOv->visible = 0; } catch (const _com_error&) {}
                        g_vHidden.push_back(j);
                    }
                    // Claimed either way, so the next plant along cannot pair with an
                    // overlay this one has already dealt with.
                    vBox[(size_t)j].bUsed = true;
                    ++nDead;
                    break;
                }
                if ((int)g_vPlan.size() + 1 >= SWAY_MAX_OBJ) break;
                Plan po = pl;
                po.nObj = j;
                po.kind = 1 /*SWAY_FOLIAGE*/;
                po.sw = b.w; po.sh = b.h;
                po.ltx = b.ltx; po.lty = b.lty;
                po.rcClump.left = po.rcClump.top = po.rcClump.right = po.rcClump.bottom = 0;
                po.nClumpIdx = -1;
                po.uHash = 0;              // never share: its lean depends on its offset
                po.nPivotRow = b.h - 1;    // its own base, which is mid-plant
                // How far above the plant's base its own base sits. The shear adds this to
                // every row, so the overlay picks the lean up exactly where the stalk's
                // head left it instead of restarting from zero and shearing out of line.
                po.nBaseOffset = pl.sh - b.h;
                po.fPhase = pl.fPhase;
                vBox[(size_t)j].bUsed = true;
                g_vPlan.push_back(po);
                ++nPaired;
                break;
            }
        }
        if (pClump) {
            for (int c = 0; c < pClump->nCount && c < CLUMP_MAX
                            && (int)g_vPlan.size() < SWAY_MAX_OBJ; ++c) {
                Plan pc = pl;
                pc.rcClump.left   = pClump->a[c].x0;
                pc.rcClump.top    = pClump->a[c].y0;
                pc.rcClump.right  = pClump->a[c].x1 + 1;   // half open, as the projection wants
                pc.rcClump.bottom = pClump->a[c].y1 + 1;
                // Each plant on its own beat. Without this a row of mushrooms sways as one
                // object, which is most of what made a spliced sprite still look wrong.
                pc.nClumpIdx = c;
                pc.fPhase = (float)(((i * 2654435761u) + (unsigned)c * 40503u) % 6283u) / 1000.0f;
                g_vPlan.push_back(pc);
            }
        } else {
            g_vPlan.push_back(pl);
        }
    }

    LOG_ONCE_PER_ID(Weather_CurrentFieldId(),
        "weathersway: map %d, %d objs, %d sway-kind, dropped: %d no-layer, %d geom, "
        "%d not-rooted, +%d head overlays, %d overlays switched off -> %u plans",
        Weather_CurrentFieldId(), n, nSeen, nNoLayer, nBadGeom, nNotRooted, nPaired, nDead,
        (unsigned)g_vPlan.size());

    // Join the columns. O(n^2) over rope segments only, which is a handful per map.
    for (size_t a = 0; a < g_vPlan.size(); ++a) {
        if (g_vPlan[a].kind != 2 /*SWAY_ROPE*/ || g_vPlan[a].nBaseOffset != 0) {
            continue;
        }
        // Everything in this column, including a itself.
        std::vector<size_t> col;
        for (size_t b = 0; b < g_vPlan.size(); ++b) {
            if (g_vPlan[b].kind != 2) {
                continue;
            }
            const int dx = g_vPlan[b].ltx + g_vPlan[b].sw / 2
                         - (g_vPlan[a].ltx + g_vPlan[a].sw / 2);
            if (dx > -SWAY_STACK_DX && dx < SWAY_STACK_DX) {
                col.push_back(b);
            }
        }
        if (col.size() < 2) {
            continue;
        }
        // The column hangs from its TOP, so the anchor is the smallest y and a segment's
        // offset is how far BELOW that anchor its own top row sits. Every segment then
        // continues the bend from exactly where the one above it left off, which is what
        // keeps a long ladder a single curve rather than a stack of independent leans.
        int nCeil = INT_MAX;
        for (size_t k : col) {
            if (g_vPlan[k].lty < nCeil) {
                nCeil = g_vPlan[k].lty;
            }
        }
        // How long the whole column is, so the rigid head can be a fraction of the ROPE
        // rather than of whichever segment a row happens to belong to.
        int nFloor = INT_MIN;
        for (size_t k : col) {
            const int nBot = g_vPlan[k].lty + g_vPlan[k].sh;
            if (nBot > nFloor) nFloor = nBot;
        }
        const int nRigid = (int)((float)(nFloor - nCeil) * SWAY_ROPE_RIGID_FRAC);
        const float fPhase = g_vPlan[col[0]].fPhase;
        // ONE TIMING FOR THE WHOLE COLUMN. Phase was already shared; rate, swing width and
        // harmonic phase were not, and those are what made a ladder read as a stack of
        // independently wobbling rungs instead of one bending object. Keying every segment
        // on the top one -- and on the column's full height, not a rung's -- makes the
        // whole ladder move as a single piece.
        const int nTimingObj = g_vPlan[col[0]].nObj;
        const int nTimingH = nFloor - nCeil;
        for (size_t k : col) {
            g_vPlan[k].nBaseOffset = g_vPlan[k].lty - nCeil;
            g_vPlan[k].nRigidDepth = nRigid;
            g_vPlan[k].fPhase = fPhase;      // one phase, or the joints still shear apart
            g_vPlan[k].nTimingObj = nTimingObj;
            g_vPlan[k].nTimingH = nTimingH;
        }
        DEBUG_MESSAGE("weathersway: joined a column of %u rope segments",
                      (unsigned)col.size());
    }
}

void Restore(SwayObj& s) {
    for (int i = 0; i < SWAY_FRAMES; ++i) {
        Release(s.apFrame[i]);
    }
    IWzGr2DLayerPtr pObj;
    POINT pt = {0, 0};
    if (Weather_GetObj(s.nObj, pObj, &pt) && pObj) {
        try { pObj->visible = 1; } catch (const _com_error&) {}
    }
}

}  // namespace


bool WeatherSway_Active() {
    return g_bUsable && !g_v.empty();
}


void WeatherSway_Frame() {
    if (!g_bBuilt) {
        g_bBuilt = true;
        g_bUsable = WeatherCanvas_Probe();
        if (g_bUsable) {
            BuildPlan();
        }
        g_nScan = g_bUsable ? 0 : -1;
    }
    // Spread the build over frames. The map has just loaded and the player is looking at
    // it; a third of a second of canvas generation in one frame is a stall they will see.
    if (g_nScan >= 0) {
        const int n = (int)g_vPlan.size();
        int nDone = 0;
        while (g_nScan < n && nDone < SWAY_BUILD_PER_FRAME
               && g_nPixels < SWAY_PIXEL_BUDGET) {
            SwayObj s;
            if (BuildFrames(g_vPlan[g_nScan], &s)) {
                g_v.push_back(s);
            }
            ++g_nScan;
            ++nDone;               // count the ATTEMPT: a failure costs the same work
        }
        if (g_nScan >= n || g_nPixels >= SWAY_PIXEL_BUDGET) {
            const bool bCut = (g_nScan < n);
            g_nScan = -1;
            // Say so when the budget stopped it early: a silent cap reads in game as
            // "some bushes just do not sway", which is exactly the report that started
            // this, and there would be nothing to distinguish it from a filter miss.
            DEBUG_MESSAGE("weathersway: %u objects bend, %d KB of frames%s",
                          (unsigned)g_v.size(), g_nPixels * 4 / 1024,
                          bCut ? " (stopped early: budget)" : "");
            // In the LOG too, not only the debug build. "nothing sways" and "everything
            // sways but you cannot see it" look identical on screen and are completely
            // different bugs; this is the line that tells them apart.
            // Per MAP. A plain LOG_ONCE fired on the first stage that ran a build, which
            // is the login screen, and reported "0 of 0" -- true, useless, and it looked
            // like an answer about Henesys.
            // How many SEPARATE bending copies each object ended up with. A sprite that
            // is not spliced should have exactly one; two means something is building the
            // plant twice, and since the two carry different phases they slide against
            // each other and read as a duplicated head.
            {
                int nDup = 0, nWorst = 0, nWorstObj = -1;
                for (size_t a = 0; a < g_v.size(); ++a) {
                    int c = 0;
                    for (size_t b = 0; b < g_v.size(); ++b) {
                        if (g_v[b].nObj == g_v[a].nObj) ++c;
                    }
                    if (c > 1) ++nDup;
                    if (c > nWorst) { nWorst = c; nWorstObj = g_v[a].nObj; }
                }
                LOG_ONCE_PER_ID(Weather_CurrentFieldId(),
                    "weathersway: map %d, %d of %u entries share an object; worst obj %d has %d",
                    Weather_CurrentFieldId(), nDup, (unsigned)g_v.size(), nWorstObj, nWorst);
            }
            LOG_ONCE_PER_ID(Weather_CurrentFieldId(),
                     "weathersway: map %d, %u of %u planned objects bend, %d KB of frames%s",
                     Weather_CurrentFieldId(),
                     (unsigned)g_v.size(), (unsigned)g_vPlan.size(),
                     g_nPixels * 4 / 1024, bCut ? " (stopped early: budget)" : "");
        }
    }
    if (g_v.empty()) {
        return;
    }

    const unsigned char uSky = Weather::CurrentSky();
    const bool bRough = (uSky == Weather::SKY_STORM || uSky == Weather::SKY_BLIZZARD
                      || uSky == Weather::SKY_SANDSTORM);
    const float fPeriod = bRough ? SWAY_PERIOD_ROUGH : SWAY_PERIOD_CALM;
    const DWORD dwTick = GetTickCount();
    const float fT = (float)(dwTick % 600000u) * 0.001f;   // seconds, wrapped every 10 min

    // THE GUST. One slow envelope over the whole map, so the wind rises and falls instead
    // of blowing at one strength forever. Two incommensurable periods rather than one, so
    // it never repeats on a beat the eye can pick up. It scales how far plants swing, not
    // how fast: a gust moves things further, it does not speed time up.
    const float fGust = 0.72f + 0.28f * (0.6f * sinf(fT * 0.181f)
                                       + 0.4f * sinf(fT * 0.067f + 1.7f));

    for (SwayObj& s : g_v) {
        // Per object, because a big sprite has fewer frames to swing through.
        const int nMidO = s.nFrames / 2;
        // Fair weather takes its share of the half-range; high wind takes most of it.
        const float fFrac = bRough ? SWAY_ROUGH_FRAC : ((float)s.uSpanPct * 0.01f);
        int nSpan = (int)lroundf((float)nMidO * fFrac);
        if (nSpan > nMidO) nSpan = nMidO;
        if (nSpan < 1) nSpan = 1;
        // This plant's own clock. fRate is 2*pi per scaled period, so a tall plant's angle
        // advances more slowly than a shrub's from the same tick.
        const float fAng = fT * (s.fRate * 1000.0f / fPeriod) + s.fPhase;
        // A pure sine is what makes an animation look like an animation. A small second
        // harmonic at its own phase gives the swing a slightly uneven return, which is
        // most of what reads as "fluid" -- it costs one more sinf per plant per frame.
        const float fWave = (1.0f - SWAY_WOBBLE) * sinf(fAng)
                          + SWAY_WOBBLE * sinf(fAng * 2.0f + s.fWobble);
        const float fAmp = (float)nSpan * (bRough ? 1.0f : fGust);
        int idx = nMidO + (int)lroundf(fAmp * fWave);
        if (idx < 0) idx = 0;
        if (idx >= s.nFrames) idx = s.nFrames - 1;
        // KEEP THE ORIGINAL HIDDEN, every frame.
        //
        // It is hidden once when its frames are built, and that is not enough: the engine
        // owns that layer and puts its visibility back on its own schedule -- the same
        // reason the night tint has to be re-asserted rather than written once. When it
        // comes back it sits unbent behind the swaying copy, and the mismatch is widest at
        // the TOP where the lean is greatest, which reads as a second copy of the plant's
        // head rather than as a plant that failed to disappear.
        {
            IWzGr2DLayerPtr pOrig;
            POINT ptOrig = {0, 0};
            if (Weather_GetObj(s.nObj, pOrig, &ptOrig) && pOrig) {
                try {
                    if (pOrig->visible) {
                        pOrig->visible = 0;
                    }
                } catch (const _com_error&) {
                }
            }
        }
        if (idx == s.nShown) {
            continue;
        }
        try {
            if (s.nShown >= 0 && s.apFrame[s.nShown]) {
                s.apFrame[s.nShown]->visible = 0;
            }
            if (s.apFrame[idx]) {
                // The night tint, applied here because these layers are ours and the
                // scenery pass in weather.cpp only walks the map's own.
                // Through the lamps, not the uniform tint: these layers are ours, so the
                // weather module's relight pass cannot see them.
                s.apFrame[idx]->color =
                        Lamps_SceneryColorAt((float)s.nLitX, (float)s.nLitY);
                s.apFrame[idx]->visible = 1;
            }
            s.nShown = idx;
        } catch (const _com_error&) {
        }
    }
}


void WeatherSway_Shutdown() {
    for (SwayObj& s : g_v) {
        Restore(s);
    }
    // Hand back the overlays we switched off. Same shape as Restore's un-hide, and subject
    // to the same caveat: on a field teardown the object list is already gone, so this is a
    // no-op there and the layers die with the map. It matters on the paths where the map
    // survives us -- a graphics-detail rebuild -- because an overlay left at visible = 0
    // with no plan to own it could never be turned back on.
    for (int nObj : g_vHidden) {
        IWzGr2DLayerPtr pObj;
        POINT pt = {0, 0};
        if (Weather_GetObj(nObj, pObj, &pt) && pObj) {
            try { pObj->visible = 1; } catch (const _com_error&) {}
        }
    }
    g_vHidden.clear();
    g_v.clear();
    g_vPlan.clear();
    g_nPixels = 0;
    g_vFrameCache.clear();
    g_bBuilt = false;
    g_bUsable = false;
    g_nScan = -1;
}
